export interface Cargas {
    idCarga: number,
    idProveedor: number,
    idPO: number,
    peso: number,
    numCajas: number,
    numPallets: number,
    temperatura: number,
    fechaDescarga: Date,
    precioCliente: number,
    costoProveedor: number,
    estatusCarga: string,
    estatusPago: string,
    comisionBroker: number,
    metodoPago: number,
    idAgenciaAduanal: number,
    placasTractor: string,
    ecoTractor: string,
    codigoAlpha: any,
    caat: any,
    ecoThermo: any,
    placas: any,
    pies: any,
    nombreOperador: string,
    numOperador: any
}
